import type { PlainEmpenho } from "@/modules/empenhos/types";

export const SAMPLE_EMPENHOS: PlainEmpenho[] = [
  {
    id: "sample-1",
    numeroEmpenho: "1120/2026",
    tipoEmpenho: "Ordinário",
    dataEmpenho: new Date(2026, 4, 4, 12),
    dataEmpenhoIso: "2026-05-04T15:00:00.000Z",
    ano: 2026,
    mes: 5,
    ficha: "Saúde",
    credor: "CONSORCIO INTERMUNICIPAL DE SAUDE",
    fonte: "Recursos vinculados",
    codigoAplicacao: "Saúde",
    valorEmpenhado: 128500,
    valorAnulado: 0,
    valorLiquidado: 84200,
    valorLiquidadoAnulado: 0,
    valorPago: 64200,
    valorPagoAnulado: 0,
    valorALiquidar: 44300,
    valorLiquidadoAPagar: 20000,
    valorAPagar: 64300,
    historico: "Serviços de atendimento especializado de saúde para pacientes encaminhados pela rede municipal.",
    historicoMascarado: "Serviços de atendimento especializado de saúde para pacientes encaminhados pela rede municipal.",
    processoCompra: "PC-045/2026",
    modalidadeLicitacao: "Credenciamento",
    processoLicitatorio: "PL-018/2026",
    numeroModalidade: "018/2026",
    pedidoCompra: "234/2026",
    contrato: "Contrato 12/2026",
    aditamento: null,
    gestor: "Secretaria Municipal de Saúde",
    categoria: "Saúde",
    secretariaEstimada: "Saúde",
    status: "Parcial",
    riskScore: 65,
    riskLevel: "Alto",
    alertas: [
      {
        tipo: "Valor elevado para o mês",
        nivel: "Alto",
        descricao: "O empenho está entre os maiores valores do mês.",
        sugestaoFiscalizacao: "Conferir justificativa, processo de compra e documentação de entrega."
      }
    ],
    documentosPagamento: []
  },
  {
    id: "sample-2",
    numeroEmpenho: "1188/2026",
    tipoEmpenho: "Ordinário",
    dataEmpenho: new Date(2026, 4, 8, 12),
    dataEmpenhoIso: "2026-05-08T15:00:00.000Z",
    ano: 2026,
    mes: 5,
    ficha: "Educação",
    credor: "COOPERATIVA DE PRODUTORES RURAIS",
    fonte: "Educação",
    codigoAplicacao: "Merenda",
    valorEmpenhado: 42600,
    valorAnulado: 0,
    valorLiquidado: 42600,
    valorLiquidadoAnulado: 0,
    valorPago: 42600,
    valorPagoAnulado: 0,
    valorALiquidar: 0,
    valorLiquidadoAPagar: 0,
    valorAPagar: 0,
    historico: "Aquisição de gêneros alimentícios para alimentação escolar.",
    historicoMascarado: "Aquisição de gêneros alimentícios para alimentação escolar.",
    processoCompra: "PC-051/2026",
    modalidadeLicitacao: "Pregão",
    processoLicitatorio: "PL-021/2026",
    numeroModalidade: "006/2026",
    pedidoCompra: "255/2026",
    contrato: null,
    aditamento: null,
    gestor: "Secretaria Municipal de Educação",
    categoria: "Alimentação / Merenda",
    secretariaEstimada: "Educação",
    status: "Pago",
    riskScore: 20,
    riskLevel: "Baixo",
    alertas: [],
    documentosPagamento: []
  },
  {
    id: "sample-3",
    numeroEmpenho: "1211/2026",
    tipoEmpenho: "Estimativo",
    dataEmpenho: new Date(2026, 4, 11, 12),
    dataEmpenhoIso: "2026-05-11T15:00:00.000Z",
    ano: 2026,
    mes: 5,
    ficha: "Administração",
    credor: "POSTO ITANHANDU LTDA",
    fonte: "Recursos próprios",
    codigoAplicacao: "Frota",
    valorEmpenhado: 78500,
    valorAnulado: 0,
    valorLiquidado: 25200,
    valorLiquidadoAnulado: 0,
    valorPago: 25200,
    valorPagoAnulado: 0,
    valorALiquidar: 53300,
    valorLiquidadoAPagar: 0,
    valorAPagar: 53300,
    historico: "Abastecimento de veículos da frota municipal com gasolina, etanol e diesel.",
    historicoMascarado: "Abastecimento de veículos da frota municipal com gasolina, etanol e diesel.",
    processoCompra: "PC-038/2026",
    modalidadeLicitacao: "Pregão",
    processoLicitatorio: "PL-015/2026",
    numeroModalidade: "004/2026",
    pedidoCompra: "210/2026",
    contrato: "Contrato 08/2026",
    aditamento: "Aditivo 01/2026",
    gestor: "Administração",
    categoria: "Combustível e Frota",
    secretariaEstimada: "Administração / Frota",
    status: "Parcial",
    riskScore: 72,
    riskLevel: "Alto",
    alertas: [
      {
        tipo: "Contrato com aditamento",
        nivel: "Médio",
        descricao: "O empenho informa aditamento contratual.",
        sugestaoFiscalizacao: "Conferir termo aditivo, prazo, valor e justificativa."
      }
    ],
    documentosPagamento: []
  },
  {
    id: "sample-4",
    numeroEmpenho: "1302/2026",
    tipoEmpenho: "Ordinario",
    dataEmpenho: new Date(2026, 4, 14, 12),
    dataEmpenhoIso: "2026-05-14T15:00:00.000Z",
    ano: 2026,
    mes: 5,
    ficha: "Administracao",
    credor: "SERVIDOR MUNICIPAL",
    fonte: "Recursos proprios",
    codigoAplicacao: "Administracao",
    valorEmpenhado: 980,
    valorAnulado: 0,
    valorLiquidado: 980,
    valorLiquidadoAnulado: 0,
    valorPago: 980,
    valorPagoAnulado: 0,
    valorALiquidar: 0,
    valorLiquidadoAPagar: 0,
    valorAPagar: 0,
    historico: "Pagamento de diaria ao servidor para viagem a Belo Horizonte para participacao em capacitacao tecnica.",
    historicoMascarado: "Pagamento de diaria ao servidor para viagem a Belo Horizonte para participacao em capacitacao tecnica.",
    processoCompra: "DIARIA-014/2026",
    modalidadeLicitacao: null,
    processoLicitatorio: null,
    numeroModalidade: null,
    pedidoCompra: null,
    contrato: null,
    aditamento: null,
    gestor: "Administracao",
    categoria: "Servicos Administrativos",
    secretariaEstimada: "Administracao",
    status: "Pago",
    riskScore: 30,
    riskLevel: "Médio",
    alertas: [
      {
        tipo: "Verificar documentos de viagem",
        nivel: "Médio",
        descricao: "Despesa de diaria ou deslocamento identificada pelo historico.",
        sugestaoFiscalizacao: "Conferir autorizacao da viagem, justificativa, comprovantes e relatorio de atividades."
      }
    ],
    documentosPagamento: []
  }
];
